[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
moros_cup = "4S2EvdGrbKJ9zazvB4gtR83crTrVJWqqwoVVvEQy8VE9"

[programs.devnet]
moros_cup = "4S2EvdGrbKJ9zazvB4gtR83crTrVJWqqwoVVvEQy8VE9"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
