import { PublicKey } from "@solana/web3.js";
import {
  PYTH_PUSH_ORACLE_PROGRAM_ADDRESS,
  STORK_ORACLE_PROGRAM_ADDRESS,
  SWITCHBOARD_QUOTE_PROGRAM_ADDRESS,
} from "nortia-client/oracles";

export const NORTIA_PROGRAM_ADDRESS = "4S2EvdGrbKJ9zazvB4gtR83crTrVJWqqwoVVvEQy8VE9";
export const TXLINE_PROGRAM_ADDRESS = "6pW64gN1s2uqjHkn1unFeEjAwJkPGHoppGvS715wyP2J";
export const PYTH_RECEIVER_PROGRAM_ADDRESS = "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ";
export const DEVNET_USDC_MINT_ADDRESS = "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU";
export const DEPLOYED_REPLAY_MARKET_ADDRESS = "44cD1kbvuheo5wSM4gxEZvAfitAXbC25f2u4Mzs48qix";

export const NORTIA_PROGRAM_KEY = new PublicKey(NORTIA_PROGRAM_ADDRESS);
export const TXLINE_PROGRAM_KEY = new PublicKey(TXLINE_PROGRAM_ADDRESS);
export const PYTH_RECEIVER_PROGRAM_KEY = new PublicKey(PYTH_RECEIVER_PROGRAM_ADDRESS);
export const PYTH_PUSH_ORACLE_PROGRAM_KEY = new PublicKey(PYTH_PUSH_ORACLE_PROGRAM_ADDRESS);
export const SWITCHBOARD_QUOTE_PROGRAM_KEY = new PublicKey(SWITCHBOARD_QUOTE_PROGRAM_ADDRESS);
export const STORK_ORACLE_PROGRAM_KEY = new PublicKey(STORK_ORACLE_PROGRAM_ADDRESS);
export const DEVNET_USDC_MINT_KEY = new PublicKey(DEVNET_USDC_MINT_ADDRESS);
