use anchor_lang::prelude::*;

pub const PROTOCOL_SEED: &[u8] = b"protocol";
pub const MARKET_SEED: &[u8] = b"market";
pub const VAULT_SEED: &[u8] = b"vault";
pub const ORDER_SEED: &[u8] = b"order";
pub const CLAIM_SEED: &[u8] = b"claim";
pub const ENGINE_SEED: &[u8] = b"engine-v2";
pub const HYBRID_MARKET_SEED: &[u8] = b"hybrid-market-v2";
pub const HYBRID_VAULT_SEED: &[u8] = b"hybrid-vault-v2";
pub const ORACLE_CONFIG_SEED: &[u8] = b"oracle-config-v2";
pub const POSITION_SEED: &[u8] = b"position-v2";
pub const RESOLUTION_RECEIPT_SEED: &[u8] = b"resolution-receipt-v2";
pub const DAILY_SCORES_ROOT_SEED: &[u8] = b"daily_scores_roots";
pub const COMMITTEE_SIZE: usize = 3;
pub const COMMITTEE_THRESHOLD: usize = 2;
pub const USDC_DECIMALS: u8 = 6;
pub const TICKET_AMOUNT: u64 = 1_000_000;
pub const MAX_PROTOCOL_FEE_BPS: u16 = 300;
pub const MAX_KEEPER_REWARD_BPS: u16 = 5_000;
pub const BASIS_POINTS_DENOMINATOR: u128 = 10_000;
pub const PARTICIPANT_ONE_GOALS_KEY: u32 = 1;
pub const PARTICIPANT_TWO_GOALS_KEY: u32 = 2;
pub const MAX_TOTAL_GOALS_THRESHOLD: i32 = 20;
pub const FEE_SPLIT_DENOMINATOR: u16 = 10_000;
pub const DEFAULT_TREASURY_FEE_SHARE_BPS: u16 = 7_000;
pub const HYBRID_ROUNDING_RESERVE: u64 = 2;
pub const FINAL_PERIOD: i32 = 100;
pub const MILLIS_PER_DAY: i64 = 86_400_000;
pub const TXLINE_VALIDATE_STAT_V2_DISCRIMINATOR: [u8; 8] = [208, 215, 194, 214, 241, 71, 246, 178];
pub const PROTOCOL_AUTHORITY: Pubkey = pubkey!("5yFHYFS1y8hVuVte6F3ae9NMh3i4F1ZGyTynwb8onb5S");
pub const DEVNET_USDC_MINT: Pubkey = pubkey!("4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU");
pub const TXLINE_PROGRAM_ID: Pubkey = pubkey!("6pW64gN1s2uqjHkn1unFeEjAwJkPGHoppGvS715wyP2J");
pub const PYTH_RECEIVER_PROGRAM_ID: Pubkey = pubkey!("rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ");
pub const SWITCHBOARD_QUOTE_PROGRAM_ID: Pubkey =
    pubkey!("orac1eFjzWL5R3RbbdMV68K9H6TaCVVcL6LjvQQWAbz");
